### ISSUE TITLE
About Figure 1

### ISSUE THREAD

**Issue by seeyourmind** [AKuzina/dct_vae#1]
Hi, I would like to know how you created the Figure 1, such as the tools and techniques you used. I'm a novice, and your insights could be really helpful for me.

**Comment by AKuzina** [comment]
Hi, Figure 1 is a matplotlib plot. If you mean Figure 3 with the architecture details, I used keynote to create it.

**Comment by seeyourmind** [comment]
More specifically, I want to know how to draw this figure. I guess that I need to compute the expectation of $D_{KL}$ for each category and then take the mean of all categories.

**Comment by AKuzina** [comment]
I am not sure I understand what you mean by category. There are curves for 4 different models, which are completely independent. 
Now, consider a single curve. I calculate $E_x D_{KL}[q(z|x) || p(z) ] = \frac{1}{N} \sum_{n} D_{KL}[q(z|x_n) || p(z) ]$, where $z = [z_1, \dots, z_L]$. This gives me a vector of KL values for each latent unit. Then, I plot a CDF of those values. I did that with the [step](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.step.html)  function. However, you can also use the [hist](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.hist.html#matplotlib.pyplot.hist) function, which has an argument to plot the cumulative histogram.

**Comment by seeyourmind** [comment]
Thank you very much for your patient response and explanation, now I understand.
